apiVersion: v1
kind: Namespace
metadata:
  name: ckad
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckad-back
  namespace: ckad
  labels:
    app: ckad-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: ckad-backend
  template:
    metadata:
      labels:
        app: ckad-backend
        name: ckad-backend
    spec:
      containers:
        - name: ckad-backend
          image: jalcina/ckad-back:latest
          env:
            - name: APP_PORT
              value: "3000"
            - name: DB_HOST
              value: "sqlservertemp2.mysql.database.azure.com"
            - name: DB_USER
              value: "jalcina@sqlservertemp2"
            - name: DB_PASS
              value: "Chucoclave123"
            - name: DB_NAME
              value: "mydb"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /ready-check
              port: 3000
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health-check
              port: 3000
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ckad-backend-service
  namespace: ckad
spec:
  type: NodePort
  selector:
    app: ckad-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000